name: Daily Fantasy NBA Update

# Schedule daily at 8 AM AEDT (21:00 UTC) and allow manual runs
on:
  schedule:
    - cron: '0 21 * * *' # 21:00 UTC = 8 AM AEDT
  workflow_dispatch:

jobs:
  run-daily-update:
    runs-on: ubuntu-latest

    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: pip install pandas numpy requests gspread google-auth slack_sdk

      # Step 4: Run the daily update script
      - name: Run daily Fantasy NBA update
        run: python daily_update.py
